import 'rxjs/add/operator/first'
import 'rxjs/add/operator/toPromise'
import 'zone.js/dist/zone'
// import 'hammerjs'
import 'popper.js'

import '@angular/common'
import '@angular/core'
import '@angular/flex-layout'
// import '@angular/forms'
// import '@angular/material'
import '@angular/router'
import '@angular/platform-browser'
import '@angular/platform-browser/animations'
