import 'rxjs/add/operator/first'
import 'rxjs/add/operator/toPromise'
import 'zone.js/dist/zone'
import 'popper.js'

import '@angular/common'
import '@angular/core'
import '@angular/flex-layout'
import '@angular/router'
import '@angular/platform-browser'
import '@angular/platform-browser/animations'
